{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "**What happened**:\r\n\r\nWhen an issue happens at the following check in the conformance test \"validates resource limits of pods that are allowed to run\":\r\n```\r\nframework.ExpectEqual(len(scheduledPods), expectedScheduled, printOnce(fmt.Sprintf(\"Scheduled Pods: %#v\", scheduledPods)))\r\n```\r\n\r\nthe debugging message (\"Scheduled Pods: %#v\") doesn't appear in the log at all like the following:\r\n```\r\n[sig-scheduling] SchedulerPredicates [Serial]\r\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:23\r\n  validates resource limits of pods that are allowed to run  [Conformance] [It]\r\n  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699\r\n\r\n  Expected\r\n      <int>: 1\r\n  to equal\r\n      <int>: 2\r\n````\r\nand that makes debugging difficult actually.\r\n\r\n**What you expected to happen**:\r\n\r\nThe debugging message should appear in the log if an issue happens.\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): v1.15.1\r\n- Cloud provider or hardware configuration: OpenStack\r\n- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.1 LTS\r\n- Kernel (e.g. `uname -a`): 4.15.0-55-generic\r\n- Install tools: kubeadm\r\n- Network plugin and version (if this is a network-related bug):\r\n- Others:\r\n",
  "closed_at": "2019-08-09T02:36:18Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 1,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/81202/comments",
  "created_at": "2019-08-08T22:46:22Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/81202/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/81202",
  "id": 478719893,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Scheduling.",
      "id": 125550211,
      "name": "sig/scheduling",
      "node_id": "MDU6TGFiZWwxMjU1NTAyMTE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/scheduling"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Testing.",
      "id": 483069764,
      "name": "sig/testing",
      "node_id": "MDU6TGFiZWw0ODMwNjk3NjQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/testing"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/81202/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0Nzg3MTk4OTM=",
  "number": 81202,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "printOnce() makes debugging difficult in a conformance test",
  "updated_at": "2019-08-09T02:36:18Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/81202",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1287154?v=4",
    "events_url": "https://api.github.com/users/oomichi/events{/privacy}",
    "followers_url": "https://api.github.com/users/oomichi/followers",
    "following_url": "https://api.github.com/users/oomichi/following{/other_user}",
    "gists_url": "https://api.github.com/users/oomichi/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/oomichi",
    "id": 1287154,
    "login": "oomichi",
    "node_id": "MDQ6VXNlcjEyODcxNTQ=",
    "organizations_url": "https://api.github.com/users/oomichi/orgs",
    "received_events_url": "https://api.github.com/users/oomichi/received_events",
    "repos_url": "https://api.github.com/users/oomichi/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/oomichi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oomichi/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/oomichi"
  }
}