{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "<!-- This form is for bug reports and feature requests ONLY! \r\n\r\nIf you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).\r\n-->\r\n\r\n**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n\r\n/kind bug\r\n\r\n**What happened**:\r\n\r\nFC plugin returns TargetWWNs at GetVolumeName(), but TargetWWNs are not unique identifier if user has multiple volumes from same target wwn.\r\nAs a result, after introducing attach/detach functions, FC plugin always fails to attach volumes if a pod requests 2+ luns.\r\n\r\n```\r\nI0918 21:42:19.353094   31402 operation_generator.go:684] Controller attach succeeded for volume \"pv0001\" (UniqueName: \"kubernetes.io/fc/[wwn]\") pod \"nginx-pod1\" (UID: \"a4e0a0a8-9cdb-11e7-804f-f8bc12550954\") device path: \"\"\r\n```\r\nThe GetVolumeName() is called from GetUniqueVolumeNameFromSpec() during Pod creation.\r\nFC plugin should return unique identifier in the GetVolumeName().\r\n\r\nIf user uses WWID to specify FC volume, this problem doesn't happen because the WWID is unique identifier.\r\n\r\n**What you expected to happen**:\r\n\r\nAll FC volumes are attached to pod.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\n\r\n- Create two PVs and PVCs which uses same target wwn.\r\n- Create Pod with these two PVCs\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`):\r\n```\r\nClient Version: version.Info{Major:\"1\", Minor:\"9+\", GitVersion:\"v1.9.0-alpha.0.723+8ca1d9f19ba2c7-dirty\", GitCommit:\"8ca1d9f19ba2c75dfbca058ecfeb11d4b39d9e9f\", GitTreeState:\"dirty\", BuildDate:\"2017-09-18T18:00:44Z\", GoVersion:\"go1.8.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\nServer Version: version.Info{Major:\"1\", Minor:\"9+\", GitVersion:\"v1.9.0-alpha.0.723+8ca1d9f19ba2c7-dirty\", GitCommit:\"8ca1d9f19ba2c75dfbca058ecfeb11d4b39d9e9f\", GitTreeState:\"dirty\", BuildDate:\"2017-09-18T21:00:48Z\", GoVersion:\"go1.8.3\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\n```\r\n- Install tools: local-up-cluster.sh\r\n\r\n/cc @rootfs @jsafrane \r\n",
  "closed_at": "2017-09-20T17:01:42Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 2,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52690/comments",
  "created_at": "2017-09-19T02:15:12Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52690/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/52690",
  "id": 258674140,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Storage.",
      "id": 169428334,
      "name": "sig/storage",
      "node_id": "MDU6TGFiZWwxNjk0MjgzMzQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/storage"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52690/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUyNTg2NzQxNDA=",
  "number": 52690,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "FC plugin: Failed to attach 2+ luns",
  "updated_at": "2017-09-20T17:01:42Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/52690",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/19844283?v=4",
    "events_url": "https://api.github.com/users/mtanino/events{/privacy}",
    "followers_url": "https://api.github.com/users/mtanino/followers",
    "following_url": "https://api.github.com/users/mtanino/following{/other_user}",
    "gists_url": "https://api.github.com/users/mtanino/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/mtanino",
    "id": 19844283,
    "login": "mtanino",
    "node_id": "MDQ6VXNlcjE5ODQ0Mjgz",
    "organizations_url": "https://api.github.com/users/mtanino/orgs",
    "received_events_url": "https://api.github.com/users/mtanino/received_events",
    "repos_url": "https://api.github.com/users/mtanino/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/mtanino/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mtanino/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/mtanino"
  }
}