{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "In one of our clusters, we are not allowing containers to run images that use `VOLUME` instructions without a corresponding Kubernetes volume and volumeMount to back it. We've done this by making `/var/lib/docker/volumes` immutable (`chattr +i`). An attempt to run a pod like this results in the container creation falling, and there's no way for the pod to run successfully.\n\nWhat we're seeing is that sometimes, attempts to delete the pod result in the pod getting stuck Terminating unless you delete it with a grace period of 0. This appears to be because of the following:\n1. syncPod processes new pod and tries to create and run the container whose image has a `VOLUME`\n2. while this is happening, the PLEG relisting happens\n   1. list all containers\n   2. the list includes the \"in-flight\" container (that is about to fail creation)\n   3. in-flight container is inspected\n   4. inspection fails with something like this: `API error (500): Unknown device 27038b8e8b60506e1744c7ab15e06a3e24855fa925678e75d72b6e1fd3bd4a31`\n   5. PLEG writes pod status to pod status cache, which includes the error above\n   6. at the end of relisting, PLEG updates the global timestamp for the pod status cache\n3. syncPod finishes in error and requeues this pod\n4. 1 or more PLEG relistings happen, updating the global timestamp\n5. another iteration of the pod worker retrieves the pod status from the cache\n   1. the cache's global timestamp is newer than the last sync time for the pod worker, so the cache returns the cached status, which includes the \"Unknown device\" error\n   2. because the error is non-nil, the worker exits its loop early, not calling syncPod (https://github.com/kubernetes/kubernetes/blob/392fc6668f5536af71950f7df56fe3f89256a66b/pkg/kubelet/pod_workers.go#L125-L127)\n6. because syncPod isn't called, the pod isn't deleted\n7. repeat infinitely\n\n@kubernetes/sig-node @kubernetes/rh-cluster-infra @ironcladlou @smarterclayton \n",
  "closed_at": "2016-05-07T05:14:08Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 32,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24819/comments",
  "created_at": "2016-04-26T20:39:53Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24819/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/24819",
  "id": 151233611,
  "labels": [
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24819/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxNTEyMzM2MTE=",
  "number": 24819,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Pods can get stuck Terminating in certain situations if running a container fails",
  "updated_at": "2018-04-03T13:46:53Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24819",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/354?v=4",
    "events_url": "https://api.github.com/users/ncdc/events{/privacy}",
    "followers_url": "https://api.github.com/users/ncdc/followers",
    "following_url": "https://api.github.com/users/ncdc/following{/other_user}",
    "gists_url": "https://api.github.com/users/ncdc/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/ncdc",
    "id": 354,
    "login": "ncdc",
    "node_id": "MDQ6VXNlcjM1NA==",
    "organizations_url": "https://api.github.com/users/ncdc/orgs",
    "received_events_url": "https://api.github.com/users/ncdc/received_events",
    "repos_url": "https://api.github.com/users/ncdc/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/ncdc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ncdc/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/ncdc"
  }
}