{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "```\n+ sudo gcloud components update -q\n\nAll components are up to date.\nTraceback (most recent call last):\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py\", line 209, in <module>\n    main()\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py\", line 205, in main\n    _cli.Execute()\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py\", line 621, in Execute\n    result = args.cmd_func(cli=self, args=args)\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py\", line 1088, in Run\n    result = command_instance.Run(args)\n  File \"/usr/local/share/google/google-cloud-sdk/lib/googlecloudsdk/gcloud/sdktools/components/update.py\", line 64, in Run\n    args.component_ids, allow_no_backup=args.allow_no_backup)\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/update_manager.py\", line 494, in Update\n    with install_state.LastUpdateCheck() as update_check:\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py\", line 232, in LastUpdateCheck\n    return LastUpdateCheck(self)\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py\", line 650, in __init__\n    self._LoadData()\n  File \"/usr/local/bin/../share/google/google-cloud-sdk/./lib/googlecloudsdk/core/updater/local_state.py\", line 659, in _LoadData\n    data = json.loads(fp.read())\n  File \"/usr/lib/python2.7/json/__init__.py\", line 326, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python2.7/json/decoder.py\", line 368, in decode\n    raise ValueError(errmsg(\"Extra data\", s, end, len(s)))\nValueError: Extra data: line 1 column 102 - line 1 column 103 (char 102 - 103)\nBuild step 'Execute shell' marked build as failure\n```\n\nFiling an internal bug, disabling this step for now.\n\ncc @jlowdermilk \n",
  "closed_at": "2015-04-17T13:17:12Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/4942464?v=4",
    "events_url": "https://api.github.com/users/zmerlynn/events{/privacy}",
    "followers_url": "https://api.github.com/users/zmerlynn/followers",
    "following_url": "https://api.github.com/users/zmerlynn/following{/other_user}",
    "gists_url": "https://api.github.com/users/zmerlynn/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/zmerlynn",
    "id": 4942464,
    "login": "zmerlynn",
    "node_id": "MDQ6VXNlcjQ5NDI0NjQ=",
    "organizations_url": "https://api.github.com/users/zmerlynn/orgs",
    "received_events_url": "https://api.github.com/users/zmerlynn/received_events",
    "repos_url": "https://api.github.com/users/zmerlynn/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/zmerlynn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zmerlynn/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/zmerlynn"
  },
  "comments": 0,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/6974/comments",
  "created_at": "2015-04-17T13:12:57Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/6974/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/6974",
  "id": 69136150,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": null,
      "id": 178071252,
      "name": "area/test-infra",
      "node_id": "MDU6TGFiZWwxNzgwNzEyNTI=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/test-infra"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Highest priority. Must be actively worked on as someone's top priority right now.",
      "id": 114528068,
      "name": "priority/critical-urgent",
      "node_id": "MDU6TGFiZWwxMTQ1MjgwNjg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/critical-urgent"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/6974/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU2OTEzNjE1MA==",
  "number": 6974,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Jenkins failing during `gcloud components update -q`",
  "updated_at": "2015-04-17T13:17:12Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/6974",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/4942464?v=4",
    "events_url": "https://api.github.com/users/zmerlynn/events{/privacy}",
    "followers_url": "https://api.github.com/users/zmerlynn/followers",
    "following_url": "https://api.github.com/users/zmerlynn/following{/other_user}",
    "gists_url": "https://api.github.com/users/zmerlynn/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/zmerlynn",
    "id": 4942464,
    "login": "zmerlynn",
    "node_id": "MDQ6VXNlcjQ5NDI0NjQ=",
    "organizations_url": "https://api.github.com/users/zmerlynn/orgs",
    "received_events_url": "https://api.github.com/users/zmerlynn/received_events",
    "repos_url": "https://api.github.com/users/zmerlynn/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/zmerlynn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zmerlynn/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/zmerlynn"
  }
}