{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "CONTRIBUTOR",
  "body": "If another process is altering iptables rules at the time k8s attempts to add iptables rules it will fail with a locking error. k8s should use -w and retry after a delay.\n\nBelow, an external process (openshift-sdn-node) modifies iptables at roughly the same time and k8s fails without retrying.\n\n```\nApr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -t nat -D POSTROUTING -s 10.1.0.0/16 '!' -d 10.1.0.0/16 -j MASQUERADE\n...\nApr 27 11:40:20 ose3-master.example.com openshift-sdn-node[2058]: + iptables -I INPUT 2 -i lbr0 -m comment --comment 'traffic from docker' -j ACCEPT\nApr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661746    2237 proxier.go:337] Failed to initialize iptables: error checking rule: exit status 4: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\nApr 27 11:40:21 ose3-master.example.com openshift-node[2237]: E0427 11:40:21.661912    2237 node.go:245] WARNING: Could not modify iptables.  iptables must be mutable by this process to use services.  Do you have root permissions?\nApr 27 11:40:22 ose3-master.example.com openshift-node[2237]: I0427 11:40:22.147405    2237 failing_service_config_proxy.go:19] Failed to properly wire up services.  This can happen if you forget to launch with permissions to iptables.  Access to the following services will be impaired: \"kubernetes-ro, router, database, frontend, ruby-example, docker-registry, kubernetes\"\n```\n\nRelated to https://github.com/openshift/origin/issues/1922\n",
  "closed_at": "2015-05-14T20:20:06Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/1163175?v=4",
    "events_url": "https://api.github.com/users/smarterclayton/events{/privacy}",
    "followers_url": "https://api.github.com/users/smarterclayton/followers",
    "following_url": "https://api.github.com/users/smarterclayton/following{/other_user}",
    "gists_url": "https://api.github.com/users/smarterclayton/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/smarterclayton",
    "id": 1163175,
    "login": "smarterclayton",
    "node_id": "MDQ6VXNlcjExNjMxNzU=",
    "organizations_url": "https://api.github.com/users/smarterclayton/orgs",
    "received_events_url": "https://api.github.com/users/smarterclayton/received_events",
    "repos_url": "https://api.github.com/users/smarterclayton/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/smarterclayton/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/smarterclayton/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/smarterclayton"
  },
  "comments": 24,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/7370/comments",
  "created_at": "2015-04-27T17:34:41Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/7370/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/7370",
  "id": 71352131,
  "labels": [
    {
      "color": "fbca04",
      "default": false,
      "description": "Higher priority than priority/awaiting-more-evidence.",
      "id": 114528273,
      "name": "priority/backlog",
      "node_id": "MDU6TGFiZWwxMTQ1MjgyNzM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/backlog"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/7370/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU3MTM1MjEzMQ==",
  "number": 7370,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "iptables invocations fail if another process is modifying iptables rules",
  "updated_at": "2017-05-30T18:42:05Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/7370",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/48161?v=4",
    "events_url": "https://api.github.com/users/sdodson/events{/privacy}",
    "followers_url": "https://api.github.com/users/sdodson/followers",
    "following_url": "https://api.github.com/users/sdodson/following{/other_user}",
    "gists_url": "https://api.github.com/users/sdodson/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/sdodson",
    "id": 48161,
    "login": "sdodson",
    "node_id": "MDQ6VXNlcjQ4MTYx",
    "organizations_url": "https://api.github.com/users/sdodson/orgs",
    "received_events_url": "https://api.github.com/users/sdodson/received_events",
    "repos_url": "https://api.github.com/users/sdodson/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/sdodson/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sdodson/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/sdodson"
  }
}