{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "/kind bug\r\n\r\nKubernetes version: 1.13.1.\r\nkube-proxy mode: IPVS.\r\nSDN: flannel.\r\n\r\nWe are used services like this:\r\n```\r\n---\r\napiVersion: v1\r\nkind: Service\r\nmetadata:\r\n  name: test\r\nspec:\r\n  type: NodePort\r\n  externalIPs:\r\n    - 192.168.10.201\r\n  ports:\r\n    - name: test-port\r\n      protocol: TCP\r\n      port: 80\r\n      targetPort: test-port\r\n  selector:\r\n      app: test\r\n```\r\nwhere IP 192.168.10.201 is from our internal /24 network (in particular, our Kube nodes have IPs 192.168.10.1, 192.168.10.2 etc). Note that there is no conflicts between real IPs and virtual external ones.\r\n\r\nBefore updating from 1.12.3 to 1.13.1, it worked correctly. In partucular these IPs was accessible from other non-Kubernetes hosts from 192.168.10.0/24 network. After update kube-proxy to 1.13.1, this feature stops working: non-Kubernetes hosts cannot resolve service IPs via ARP:\r\n```\r\n# ip ne sh 192.168.10.201\r\n192.168.10.201 dev eth1  FAILED\r\n```\r\nOn Kubernetes hosts it still working, because not requires ARP resolving.\r\n\r\nIf we reset sysctl parameter arp_ignore on Kube hosts,\r\n```\r\nsysctl net.ipv4.conf.all.arp_ignore=0\r\n```\r\nall works normally even from non-Kube hosts.\r\n\r\nQuck debugging shows that problem is in the commit 489e95bc305b017dd8b61960c9e92aae130e863d. Please make this behaviour opt-out. (Now we resets arp_ignore to 0 via cron every 1 min.)",
  "closed_at": "2019-03-20T14:41:53Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 5,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/72779/comments",
  "created_at": "2019-01-10T12:47:22Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/72779/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/72779",
  "id": 397815383,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": null,
      "id": 755527763,
      "name": "area/ipvs",
      "node_id": "MDU6TGFiZWw3NTU1Mjc3NjM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/ipvs"
    },
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Network.",
      "id": 116712108,
      "name": "sig/network",
      "node_id": "MDU6TGFiZWwxMTY3MTIxMDg=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/network"
    },
    {
      "color": "d455d0",
      "default": false,
      "description": "Indicates an issue that can not or will not be resolved.",
      "id": 862108765,
      "name": "triage/unresolved",
      "node_id": "MDU6TGFiZWw4NjIxMDg3NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/triage/unresolved"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/72779/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzOTc4MTUzODM=",
  "number": 72779,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "kube-proxy v1.13.0 and 1.13.1 brokes services with externalIPs",
  "updated_at": "2019-03-20T14:41:53Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/72779",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/14880972?v=4",
    "events_url": "https://api.github.com/users/nnz1024/events{/privacy}",
    "followers_url": "https://api.github.com/users/nnz1024/followers",
    "following_url": "https://api.github.com/users/nnz1024/following{/other_user}",
    "gists_url": "https://api.github.com/users/nnz1024/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/nnz1024",
    "id": 14880972,
    "login": "nnz1024",
    "node_id": "MDQ6VXNlcjE0ODgwOTcy",
    "organizations_url": "https://api.github.com/users/nnz1024/orgs",
    "received_events_url": "https://api.github.com/users/nnz1024/received_events",
    "repos_url": "https://api.github.com/users/nnz1024/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/nnz1024/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nnz1024/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/nnz1024"
  }
}