{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "MEMBER",
  "body": "We observed in an e2e that if attach is performed on a volume that was detached before from same node, sometimes the mount of the volume (for 2nd pod) could be stuck waiting on invalid devicePath in `WaitForAttach` call.\r\n\r\n The problem is - when attach for second pod failed with `\"Error attaching EBS volume \\\"vol-xxx\\\"\" to instance \"i-xxx\" since volume is currently attached to \"i-xxx\",` this caused an dangling volume error from AWS cloudprovider(implemented by us). The dangling volume error is supposed to auto-correct any volumes which are attached to a node that it shouldn't be. But in this case - the dangling volume error was triggered by the fact that, volume was not actually attached to the node but because `describeVolume` call for 2nd attachment returned stale data (because of AWS eventual consistency). \r\n\r\nSo, dangling volume exception caused volume to be added to actual state of world (so as it can be detached later), but this caused volume to be reported to node's Status field. And that caused second pod to assume volume as attached to invalid device path and hence 2nd pod was stuck for 10 minutes waiting for volume to attach on a device path (/dev/xvdbl) which does not exist.",
  "closed_at": "2019-06-06T23:48:00Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 6,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/77949/comments",
  "created_at": "2019-05-15T18:44:43Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/77949/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/77949",
  "id": 444588978,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Storage.",
      "id": 169428334,
      "name": "sig/storage",
      "node_id": "MDU6TGFiZWwxNjk0MjgzMzQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/storage"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/77949/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU0NDQ1ODg5Nzg=",
  "number": 77949,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "On AWS Attach followed by a detach of same volume is stuck waiting for volume attachment on old device path",
  "updated_at": "2019-06-06T23:48:00Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/77949",
  "user": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/278?v=4",
    "events_url": "https://api.github.com/users/gnufied/events{/privacy}",
    "followers_url": "https://api.github.com/users/gnufied/followers",
    "following_url": "https://api.github.com/users/gnufied/following{/other_user}",
    "gists_url": "https://api.github.com/users/gnufied/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/gnufied",
    "id": 278,
    "login": "gnufied",
    "node_id": "MDQ6VXNlcjI3OA==",
    "organizations_url": "https://api.github.com/users/gnufied/orgs",
    "received_events_url": "https://api.github.com/users/gnufied/received_events",
    "repos_url": "https://api.github.com/users/gnufied/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/gnufied/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gnufied/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/gnufied"
  }
}