{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/5821883?v=4",
    "events_url": "https://api.github.com/users/Random-Liu/events{/privacy}",
    "followers_url": "https://api.github.com/users/Random-Liu/followers",
    "following_url": "https://api.github.com/users/Random-Liu/following{/other_user}",
    "gists_url": "https://api.github.com/users/Random-Liu/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/Random-Liu",
    "id": 5821883,
    "login": "Random-Liu",
    "node_id": "MDQ6VXNlcjU4MjE4ODM=",
    "organizations_url": "https://api.github.com/users/Random-Liu/orgs",
    "received_events_url": "https://api.github.com/users/Random-Liu/received_events",
    "repos_url": "https://api.github.com/users/Random-Liu/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/Random-Liu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Random-Liu/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/Random-Liu"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars3.githubusercontent.com/u/5821883?v=4",
      "events_url": "https://api.github.com/users/Random-Liu/events{/privacy}",
      "followers_url": "https://api.github.com/users/Random-Liu/followers",
      "following_url": "https://api.github.com/users/Random-Liu/following{/other_user}",
      "gists_url": "https://api.github.com/users/Random-Liu/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/Random-Liu",
      "id": 5821883,
      "login": "Random-Liu",
      "node_id": "MDQ6VXNlcjU4MjE4ODM=",
      "organizations_url": "https://api.github.com/users/Random-Liu/orgs",
      "received_events_url": "https://api.github.com/users/Random-Liu/received_events",
      "repos_url": "https://api.github.com/users/Random-Liu/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/Random-Liu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Random-Liu/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/Random-Liu"
    }
  ],
  "author_association": "MEMBER",
  "body": "I am using image `gcr.io/mixia-kube/udptest:v1`. The pod event shows `Successfully pulled image \"gcr.io/mixia-kube/udptest:v1\"`. But I got to the node and found the image is not in `docker images` list. When I manually pull  the image, pod got created successfully.\n\nThis used to work for me. Not sure if anything changes with kubelet or gcr. \n\n``` console\nName:       my-udp-rc-ld468\nNamespace:  default\nNode:       e2e-test-mixia-minion-9ou9/10.240.0.5\nStart Time: Mon, 11 Apr 2016 10:51:02 -0700\nLabels:     app=udp\nStatus:     Pending\nIP:     10.245.3.5\nControllers:    ReplicationController/my-udp-rc\nContainers:\n  udp-echo:\n    Container ID:   \n    Image:      gcr.io/mixia-kube/udptest:v1\n    Image ID:       \n    Port:       8888/UDP\n    QoS Tier:\n      memory:   BestEffort\n      cpu:  Burstable\n    Requests:\n      cpu:          100m\n    State:          Waiting\n      Reason:           RunContainerError\n    Ready:          False\n    Restart Count:      0\n    Environment Variables:  <none>\nConditions:\n  Type      Status\n  Ready     False \nVolumes:\n  default-token-ic1hj:\n    Type:   Secret (a volume populated by a Secret)\n    SecretName: default-token-ic1hj\nEvents:\n  FirstSeen LastSeen    Count   From                    SubobjectPath           Type        Reason      Message\n  --------- --------    -----   ----                    -------------           --------    ------      -------\n  34s       34s     1   {default-scheduler }                            Normal      Scheduled   Successfully assigned my-udp-rc-ld468 to e2e-test-mixia-minion-9ou9\n  34s       7s      4   {kubelet e2e-test-mixia-minion-9ou9}    spec.containers{udp-echo}   Normal      Pulling     pulling image \"gcr.io/mixia-kube/udptest:v1\"\n  33s       7s      4   {kubelet e2e-test-mixia-minion-9ou9}    spec.containers{udp-echo}   Normal      Pulled      Successfully pulled image \"gcr.io/mixia-kube/udptest:v1\"\n  33s       7s      4   {kubelet e2e-test-mixia-minion-9ou9}    spec.containers{udp-echo}   Warning     Failed      Failed to create docker container with error: Error: No such image: gcr.io/mixia-kube/udptest:v1\n  33s       7s      4   {kubelet e2e-test-mixia-minion-9ou9}                    Warning     FailedSync  Error syncing pod, skipping: failed to \"StartContainer\" for \"udp-echo\" with RunContainerError: \"runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1\"\n```\n\nkubelet.log:\n\n``` console\nI0411 17:51:02.867797    3391 server.go:609] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"my-udp-rc-ld468\", UID:\"f4d5367c-000d-11e6-95cc-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"252\", FieldPath:\"spec.containers{udp-echo}\"}): type: 'Normal' reason: 'Pulling' pulling image \"gcr.io/mixia-kube/udptest:v1\"\nI0411 17:51:02.869585    3391 config.go:155] body of failing http response: &{0xc820c4e640 {0 0} false <nil> 0x665ae0 0x665a80}\nE0411 17:51:02.869642    3391 metadata.go:112] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg\nI0411 17:51:02.869684    3391 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigUrlKeyProvider\nI0411 17:51:02.871350    3391 config.go:155] body of failing http response: &{0xc820c4eac0 {0 0} false <nil> 0x665ae0 0x665a80}\nE0411 17:51:02.871379    3391 metadata.go:124] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url\nI0411 17:51:03.046191    3391 kubelet.go:1237] container: default/my-udp-rc-ld468/udp-echo podIP: \"10.245.3.5\" creating hosts mount: true\nI0411 17:51:03.046786    3391 server.go:609] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"my-udp-rc-ld468\", UID:\"f4d5367c-000d-11e6-95cc-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"252\", FieldPath:\"spec.containers{udp-echo}\"}): type: 'Normal' reason: 'Pulled' Successfully pulled image \"gcr.io/mixia-kube/udptest:v1\"\nI0411 17:51:03.047303    3391 manager.go:625] Container default/my-udp-rc-ld468/udp-echo: setting entrypoint \"[]\" and command \"[]\"\nE0411 17:51:03.049129    3391 manager.go:1915] Error running pod \"my-udp-rc-ld468_default(f4d5367c-000d-11e6-95cc-42010af00002)\" container \"udp-echo\": runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1\nE0411 17:51:03.049180    3391 pod_workers.go:138] Error syncing pod f4d5367c-000d-11e6-95cc-42010af00002, skipping: failed to \"StartContainer\" for \"udp-echo\" with RunContainerError: \"runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1\"\nI0411 17:51:03.049219    3391 server.go:609] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"my-udp-rc-ld468\", UID:\"f4d5367c-000d-11e6-95cc-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"252\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to \"StartContainer\" for \"udp-echo\" with RunContainerError: \"runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1\"\nI0411 17:51:03.049234    3391 server.go:609] Event(api.ObjectReference{Kind:\"Pod\", Namespace:\"default\", Name:\"my-udp-rc-ld468\", UID:\"f4d5367c-000d-11e6-95cc-42010af00002\", APIVersion:\"v1\", ResourceVersion:\"252\", FieldPath:\"spec.containers{udp-echo}\"}): type: 'Warning' reason: 'Failed' Failed to create docker container with error: Error: No such image: gcr.io/mixia-kube/udptest:v1\n```\n",
  "closed_at": "2016-04-18T14:05:44Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 6,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24101/comments",
  "created_at": "2016-04-11T18:00:57Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24101/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/24101",
  "id": 147506538,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "eb6420",
      "default": false,
      "description": "Must be staffed and worked on either currently, or very soon, ideally in time for the next release.",
      "id": 114528223,
      "name": "priority/important-soon",
      "node_id": "MDU6TGFiZWwxMTQ1MjgyMjM=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/priority/important-soon"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Node.",
      "id": 173493665,
      "name": "sig/node",
      "node_id": "MDU6TGFiZWwxNzM0OTM2NjU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/node"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24101/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUxNDc1MDY1Mzg=",
  "number": 24101,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Pod in RunContainerError Status ",
  "updated_at": "2016-04-18T14:05:44Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/24101",
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/1332699?v=4",
    "events_url": "https://api.github.com/users/freehan/events{/privacy}",
    "followers_url": "https://api.github.com/users/freehan/followers",
    "following_url": "https://api.github.com/users/freehan/following{/other_user}",
    "gists_url": "https://api.github.com/users/freehan/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/freehan",
    "id": 1332699,
    "login": "freehan",
    "node_id": "MDQ6VXNlcjEzMzI2OTk=",
    "organizations_url": "https://api.github.com/users/freehan/orgs",
    "received_events_url": "https://api.github.com/users/freehan/received_events",
    "repos_url": "https://api.github.com/users/freehan/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/freehan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/freehan/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/freehan"
  }
}