{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/6629765?v=4",
    "events_url": "https://api.github.com/users/roycaihw/events{/privacy}",
    "followers_url": "https://api.github.com/users/roycaihw/followers",
    "following_url": "https://api.github.com/users/roycaihw/following{/other_user}",
    "gists_url": "https://api.github.com/users/roycaihw/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/roycaihw",
    "id": 6629765,
    "login": "roycaihw",
    "node_id": "MDQ6VXNlcjY2Mjk3NjU=",
    "organizations_url": "https://api.github.com/users/roycaihw/orgs",
    "received_events_url": "https://api.github.com/users/roycaihw/received_events",
    "repos_url": "https://api.github.com/users/roycaihw/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/roycaihw/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/roycaihw/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/roycaihw"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars1.githubusercontent.com/u/6629765?v=4",
      "events_url": "https://api.github.com/users/roycaihw/events{/privacy}",
      "followers_url": "https://api.github.com/users/roycaihw/followers",
      "following_url": "https://api.github.com/users/roycaihw/following{/other_user}",
      "gists_url": "https://api.github.com/users/roycaihw/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/roycaihw",
      "id": 6629765,
      "login": "roycaihw",
      "node_id": "MDQ6VXNlcjY2Mjk3NjU=",
      "organizations_url": "https://api.github.com/users/roycaihw/orgs",
      "received_events_url": "https://api.github.com/users/roycaihw/received_events",
      "repos_url": "https://api.github.com/users/roycaihw/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/roycaihw/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/roycaihw/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/roycaihw"
    }
  ],
  "author_association": "NONE",
  "body": "**What happened**:\r\nDeployed a webhook as a service to a Kubernetes cluster with 2 masters, listening initially on port 8000. \r\n```yaml\r\napiVersion: v1\r\nkind: Namespace\r\nmetadata:\r\n  name: webhook\r\n---\r\nkind: Service\r\napiVersion: v1\r\nmetadata:\r\n  name: webhook\r\n  namespace: webhook\r\nspec:\r\n  selector:\r\n    app: webhook\r\n  ports:\r\n  - name: https\r\n    protocol: TCP\r\n    port: 8000\r\n    targetPort: 443\r\n```\r\n\r\nCreated a Validating Webhook pointing to port 8000:\r\n```yaml\r\napiVersion: admissionregistration.k8s.io/v1beta1\r\nkind: ValidatingWebhookConfiguration\r\nmetadata:\r\n  name: validating-webhook\r\nwebhooks:\r\n- clientConfig:\r\n    caBundle: ...\r\n    service:\r\n      name: webhook\r\n      namespace: webhook\r\n      path: /validate\r\n      port: 8000\r\n  failurePolicy: Fail\r\n...\r\n```\r\n\r\nChanged the service to use port 443. As expected, pod creation started to fail with the message (not always though):\r\n```bash\r\n$ kubectl run nginx --image nginx\r\nError from server (InternalError): Internal error occurred: failed calling webhook \"webhook.webhook.svc\": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port '\u1f40' found for service \"webhook\"\r\n```\r\n\r\nThe '\u1f40' character was a bug on printing the port number - 8000 in this case - that was [fixed](https://github.com/kubernetes/kubernetes/pull/85558). This is not the issue here.\r\n\r\nAfter fixing the webhook configuration, I started seeing the message:\r\n```bash\r\n$ kubectl run nginx --image nginx\r\nError from server (InternalError): Internal error occurred: failed calling webhook \"webhook.webhook.svc\": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port '\u01bb' found for service \"webhook\"\r\n```\r\n\r\nConsistently when hitting one of the masters, while the Validating Webhook worked as expected when hitting the other master. Again the weird character '\u01bb' represents 443, the .webhooks[].clientConfig.service.port in ValidatingWebhookConfiguration.\r\n\r\nThe same issue persists after deleting the service, webhook, and recreating with the same names.\r\n\r\n**What you expected to happen**:\r\nI expected the Validating Webhook to work on both masters.\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\nTried reproducing this issue using a different service name, as well as deploying it in another cluster. But the same error didn't happen again, so I believe there was some sort of special condition that caused this problem.\r\n\r\n**Anything else we need to know?**:\r\nDigging a bit into this, I suspect it has something to do with the [caching](https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L117) . I couldn't find a reference to where this cache is cleaned up.\r\n\r\nShouldn't we move to a LRUExpireCache to avoid this?\r\n\r\nI'm happy to make a pull request if you think this is the case.\r\n\r\n**Environment**:\r\n- Kubernetes version (use `kubectl version`): 1.15 (but this code hasn't changed since)\r\n- Cloud provider or hardware configuration: AWS\r\n- OS (e.g: `cat /etc/os-release`):\r\n- Kernel (e.g. `uname -a`):\r\n- Install tools:\r\n- Network plugin and version (if this is a network-related bug):\r\n- Others:\r\n",
  "closed_at": "2020-10-15T14:10:25Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/20407524?v=4",
    "events_url": "https://api.github.com/users/k8s-ci-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-ci-robot/followers",
    "following_url": "https://api.github.com/users/k8s-ci-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-ci-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-ci-robot",
    "id": 20407524,
    "login": "k8s-ci-robot",
    "node_id": "MDQ6VXNlcjIwNDA3NTI0",
    "organizations_url": "https://api.github.com/users/k8s-ci-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-ci-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-ci-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-ci-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-ci-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-ci-robot"
  },
  "comments": 14,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/93409/comments",
  "created_at": "2020-07-24T06:41:24Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/93409/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/93409",
  "id": 664952797,
  "labels": [
    {
      "color": "0052cc",
      "default": false,
      "description": null,
      "id": 486445796,
      "name": "area/admission-control",
      "node_id": "MDU6TGFiZWw0ODY0NDU3OTY=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/area/admission-control"
    },
    {
      "color": "d455d0",
      "default": false,
      "description": "Categorizes issue or PR as a support question.",
      "id": 130318610,
      "name": "kind/support",
      "node_id": "MDU6TGFiZWwxMzAzMTg2MTA=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/support"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG API Machinery.",
      "id": 173493835,
      "name": "sig/api-machinery",
      "node_id": "MDU6TGFiZWwxNzM0OTM4MzU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/api-machinery"
    },
    {
      "color": "d455d0",
      "default": false,
      "description": "Indicates an issue needs more information in order to work on it.",
      "id": 862108635,
      "name": "triage/needs-information",
      "node_id": "MDU6TGFiZWw4NjIxMDg2MzU=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/triage/needs-information"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/93409/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWU2NjQ5NTI3OTc=",
  "number": 93409,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Webhook REST clients cache invalid and possibly not expiring",
  "updated_at": "2020-10-15T14:10:25Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/93409",
  "user": {
    "avatar_url": "https://avatars1.githubusercontent.com/u/15331190?v=4",
    "events_url": "https://api.github.com/users/raonitimo/events{/privacy}",
    "followers_url": "https://api.github.com/users/raonitimo/followers",
    "following_url": "https://api.github.com/users/raonitimo/following{/other_user}",
    "gists_url": "https://api.github.com/users/raonitimo/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/raonitimo",
    "id": 15331190,
    "login": "raonitimo",
    "node_id": "MDQ6VXNlcjE1MzMxMTkw",
    "organizations_url": "https://api.github.com/users/raonitimo/orgs",
    "received_events_url": "https://api.github.com/users/raonitimo/received_events",
    "repos_url": "https://api.github.com/users/raonitimo/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/raonitimo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/raonitimo/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/raonitimo"
  }
}