{
  "active_lock_reason": null,
  "assignee": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/24448061?v=4",
    "events_url": "https://api.github.com/users/msau42/events{/privacy}",
    "followers_url": "https://api.github.com/users/msau42/followers",
    "following_url": "https://api.github.com/users/msau42/following{/other_user}",
    "gists_url": "https://api.github.com/users/msau42/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/msau42",
    "id": 24448061,
    "login": "msau42",
    "node_id": "MDQ6VXNlcjI0NDQ4MDYx",
    "organizations_url": "https://api.github.com/users/msau42/orgs",
    "received_events_url": "https://api.github.com/users/msau42/received_events",
    "repos_url": "https://api.github.com/users/msau42/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/msau42/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/msau42/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/msau42"
  },
  "assignees": [
    {
      "avatar_url": "https://avatars3.githubusercontent.com/u/24448061?v=4",
      "events_url": "https://api.github.com/users/msau42/events{/privacy}",
      "followers_url": "https://api.github.com/users/msau42/followers",
      "following_url": "https://api.github.com/users/msau42/following{/other_user}",
      "gists_url": "https://api.github.com/users/msau42/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/msau42",
      "id": 24448061,
      "login": "msau42",
      "node_id": "MDQ6VXNlcjI0NDQ4MDYx",
      "organizations_url": "https://api.github.com/users/msau42/orgs",
      "received_events_url": "https://api.github.com/users/msau42/received_events",
      "repos_url": "https://api.github.com/users/msau42/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/msau42/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/msau42/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/msau42"
    }
  ],
  "author_association": "MEMBER",
  "body": "<!-- This form is for bug reports and feature requests ONLY! \r\n\r\nIf you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).\r\n-->\r\n\r\n**Is this a BUG REPORT or FEATURE REQUEST?**:\r\n@kubernetes/sig-storage-bugs \r\n/assign\r\n\r\n**What happened**:\r\n[Testgrid](https://k8s-testgrid.appspot.com/sig-storage#gce-serial)\r\n[Logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/3273)\r\n\r\nThe regular volume mount didn't get cleaned up:\r\n```\r\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/subpath.go:265\r\nExpected grep stdout to be empty (i.e. no mount found).\r\nExpected\r\n    <string>: /dev/sdc on /var/lib/kubelet/pods/d98b92b4-3bf7-11e8-8908-42010a800002/volumes/kubernetes.io~gce-pd/pvc-d98a660c-3bf7-11e8-8908-42010a800002 type ext4 (rw,relatime,data=ordered)\r\n    /dev/sdc on /var/lib/kubelet/pods/d98b92b4-3bf7-11e8-8908-42010a800002/volumes/kubernetes.io~gce-pd/pvc-d98a660c-3bf7-11e8-8908-42010a800002 type ext4 (rw,relatime,data=ordered)\r\n    /dev/sdc on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/d98b92b4-3bf7-11e8-8908-42010a800002/volumes/kubernetes.io~gce-pd/pvc-d98a660c-3bf7-11e8-8908-42010a800002 type ext4 (rw,relatime,data=ordered)\r\n    /dev/sdc on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/d98b92b4-3bf7-11e8-8908-42010a800002/volumes/kubernetes.io~gce-pd/pvc-d98a660c-3bf7-11e8-8908-42010a800002 type ext4 (rw,relatime,data=ordered)\r\n    \r\nto be empty\r\n/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/subpath.go:615\r\n```\r\n\r\n@jingxu97 took a look, seems like the volume did get cleaned up after the check, so looks like there's some new delay introduced in the cleanup path.  Likely suspect is https://github.com/kubernetes/kubernetes/pull/61071, although it was merged almost a month ago, and this test only started failing 3 days ago.\r\n\r\nAnyway, looks like the normal non-subpath test added an extra sleep to account for this delay.\r\n",
  "closed_at": "2018-04-16T20:56:07Z",
  "closed_by": {
    "avatar_url": "https://avatars0.githubusercontent.com/u/13653959?v=4",
    "events_url": "https://api.github.com/users/k8s-github-robot/events{/privacy}",
    "followers_url": "https://api.github.com/users/k8s-github-robot/followers",
    "following_url": "https://api.github.com/users/k8s-github-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-github-robot/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/k8s-github-robot",
    "id": 13653959,
    "login": "k8s-github-robot",
    "node_id": "MDQ6VXNlcjEzNjUzOTU5",
    "organizations_url": "https://api.github.com/users/k8s-github-robot/orgs",
    "received_events_url": "https://api.github.com/users/k8s-github-robot/received_events",
    "repos_url": "https://api.github.com/users/k8s-github-robot/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/k8s-github-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-github-robot/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/k8s-github-robot"
  },
  "comments": 0,
  "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62293/comments",
  "created_at": "2018-04-09T21:55:07Z",
  "events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62293/events",
  "html_url": "https://github.com/kubernetes/kubernetes/issues/62293",
  "id": 312701514,
  "labels": [
    {
      "color": "e11d21",
      "default": false,
      "description": "Categorizes issue or PR as related to a bug.",
      "id": 105146071,
      "name": "kind/bug",
      "node_id": "MDU6TGFiZWwxMDUxNDYwNzE=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/kind/bug"
    },
    {
      "color": "d2b48c",
      "default": false,
      "description": "Categorizes an issue or PR as relevant to SIG Storage.",
      "id": 169428334,
      "name": "sig/storage",
      "node_id": "MDU6TGFiZWwxNjk0MjgzMzQ=",
      "url": "https://api.github.com/repos/kubernetes/kubernetes/labels/sig/storage"
    }
  ],
  "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62293/labels{/name}",
  "locked": false,
  "milestone": null,
  "node_id": "MDU6SXNzdWUzMTI3MDE1MTQ=",
  "number": 62293,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/kubernetes/kubernetes",
  "state": "closed",
  "title": "Subpath graceful pod delete e2e test failing for gce pd",
  "updated_at": "2018-04-16T20:56:07Z",
  "url": "https://api.github.com/repos/kubernetes/kubernetes/issues/62293",
  "user": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/24448061?v=4",
    "events_url": "https://api.github.com/users/msau42/events{/privacy}",
    "followers_url": "https://api.github.com/users/msau42/followers",
    "following_url": "https://api.github.com/users/msau42/following{/other_user}",
    "gists_url": "https://api.github.com/users/msau42/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/msau42",
    "id": 24448061,
    "login": "msau42",
    "node_id": "MDQ6VXNlcjI0NDQ4MDYx",
    "organizations_url": "https://api.github.com/users/msau42/orgs",
    "received_events_url": "https://api.github.com/users/msau42/received_events",
    "repos_url": "https://api.github.com/users/msau42/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/msau42/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/msau42/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/msau42"
  }
}