{
  "active_lock_reason": null,
  "assignee": null,
  "assignees": [],
  "author_association": "NONE",
  "body": "<!-- **Are you in the right place?**\r\n1. For issues or feature requests, please create an issue in this repository.\r\n2. For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).\r\n3. Did you already search the existing open issues for anything similar? -->\r\n\r\n**Is this a bug report or feature request?**\r\n* Bug Report\r\n\r\n**Deviation from expected behavior:**\r\nAfter upgrade of rook from 1.2.4 to 1.2.6, the rook-ceph-osd-prepare pods fail with below error message, trying to access /dev/sda1, which should not be touched.\r\n\r\n**Expected behavior:**\r\n/dev/sda1 should be ignored, as it contains the root filesystem, and is already formatted.\r\n\r\n**How to reproduce it (minimal and precise):**\r\nI think I have nothing special, just the files as they are in the example folder.\r\n\r\n**File(s) to submit**:\r\n\r\n```\r\n2020-03-13 14:04:14.487002 I |   Type            Path                                                    LV Size         % of device\r\n2020-03-13 14:04:14.487006 I | ----------------------------------------------------------------------------------------------------\r\n2020-03-13 14:04:14.487011 I |   [data]          /dev/sda1                                               30.00 GB        100%\r\n2020-03-13 14:04:14.494915 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sda1\r\n2020-03-13 14:04:18.866356 I | Running command: /usr/sbin/vgcreate --force --yes ceph-566bf106-e66e-42ff-b4c6-7bcfdf9d227c /dev/sda1\r\n2020-03-13 14:04:19.306680 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.\r\n2020-03-13 14:04:19.307015 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.\r\n2020-03-13 14:04:19.327287 I |  stderr: Can't open /dev/sda1 exclusively.  Mounted filesystem?\r\n2020-03-13 14:04:19.328401 I |  stderr: Can't open /dev/sda1 exclusively.  Mounted filesystem?\r\n2020-03-13 14:04:19.367907 I | Traceback (most recent call last):\r\n2020-03-13 14:04:19.367920 I |   File \"/usr/sbin/ceph-volume\", line 9, in <module>\r\n2020-03-13 14:04:19.367927 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()\r\n2020-03-13 14:04:19.367932 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 39, in __init__\r\n2020-03-13 14:04:19.367941 I |     self.main(self.argv)\r\n2020-03-13 14:04:19.367949 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 59, in newfunc\r\n2020-03-13 14:04:19.367986 I |     return f(*a, **kw)\r\n2020-03-13 14:04:19.367995 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/main.py\", line 150, in main\r\n2020-03-13 14:04:19.368015 I |     terminal.dispatch(self.mapper, subcommand_args)\r\n2020-03-13 14:04:19.368028 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\r\n2020-03-13 14:04:19.368077 I |     instance.main()\r\n2020-03-13 14:04:19.368082 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py\", line 42, in main\r\n2020-03-13 14:04:19.368185 I |     terminal.dispatch(self.mapper, self.argv)\r\n2020-03-13 14:04:19.368194 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/terminal.py\", line 194, in dispatch\r\n2020-03-13 14:04:19.368200 I |     instance.main()\r\n2020-03-13 14:04:19.368204 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/decorators.py\", line 16, in is_root\r\n2020-03-13 14:04:19.368208 I |     return func(*a, **kw)\r\n2020-03-13 14:04:19.368211 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 325, in main\r\n2020-03-13 14:04:19.368215 I |     self.execute()\r\n2020-03-13 14:04:19.368219 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py\", line 288, in execute\r\n2020-03-13 14:04:19.368224 I |     self.strategy.execute()\r\n2020-03-13 14:04:19.368228 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py\", line 101, in execute\r\n2020-03-13 14:04:19.368259 I |     vg = lvm.create_vg(osd['data']['path'])\r\n2020-03-13 14:04:19.368266 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/api/lvm.py\", line 773, in create_vg\r\n2020-03-13 14:04:19.368376 I |     name] + devices\r\n2020-03-13 14:04:19.368385 I |   File \"/usr/lib/python2.7/site-packages/ceph_volume/process.py\", line 153, in run\r\n2020-03-13 14:04:19.368391 I |     raise RuntimeError(msg)\r\n2020-03-13 14:04:19.368414 I | RuntimeError: command returned non-zero exit status: 5\r\nfailed to configure devices: failed to configure devices with ceph-volume: failed to initialize devices: failed ceph-volume: Failed to complete '': exit status 1. \r\n\r\n```\r\n\r\n**Environment**:\r\n* OS (e.g. from /etc/os-release): k3os 0.9.0\r\n* Kernel (e.g. `uname -a`): Linux ceph03 5.0.0-37-generic #40~18.04.1 SMP Wed Jan 15 04:09:29 UTC 2020 x86_64 GNU/Linux\r\n\r\n* Cloud provider or hardware configuration: kvm\r\n* Rook version (use `rook version` inside of a Rook Pod): 1.2.6\r\n* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)\r\n* Kubernetes version (use `kubectl version`): v1.17.2+k3s1\r\n* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): KVM\r\n* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): \r\n",
  "closed_at": "2020-03-26T12:15:41Z",
  "closed_by": {
    "avatar_url": "https://avatars3.githubusercontent.com/u/912735?v=4",
    "events_url": "https://api.github.com/users/leseb/events{/privacy}",
    "followers_url": "https://api.github.com/users/leseb/followers",
    "following_url": "https://api.github.com/users/leseb/following{/other_user}",
    "gists_url": "https://api.github.com/users/leseb/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/leseb",
    "id": 912735,
    "login": "leseb",
    "node_id": "MDQ6VXNlcjkxMjczNQ==",
    "organizations_url": "https://api.github.com/users/leseb/orgs",
    "received_events_url": "https://api.github.com/users/leseb/received_events",
    "repos_url": "https://api.github.com/users/leseb/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/leseb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/leseb/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/leseb"
  },
  "comments": 21,
  "comments_url": "https://api.github.com/repos/rook/rook/issues/5022/comments",
  "created_at": "2020-03-13T14:15:39Z",
  "events_url": "https://api.github.com/repos/rook/rook/issues/5022/events",
  "html_url": "https://github.com/rook/rook/issues/5022",
  "id": 580628898,
  "labels": [
    {
      "color": "ee0000",
      "default": true,
      "description": "",
      "id": 405241115,
      "name": "bug",
      "node_id": "MDU6TGFiZWw0MDUyNDExMTU=",
      "url": "https://api.github.com/repos/rook/rook/labels/bug"
    }
  ],
  "labels_url": "https://api.github.com/repos/rook/rook/issues/5022/labels{/name}",
  "locked": false,
  "milestone": {
    "closed_at": "2020-09-11T22:42:52Z",
    "closed_issues": 65,
    "created_at": "2019-08-22T12:51:15Z",
    "creator": {
      "avatar_url": "https://avatars3.githubusercontent.com/u/912735?v=4",
      "events_url": "https://api.github.com/users/leseb/events{/privacy}",
      "followers_url": "https://api.github.com/users/leseb/followers",
      "following_url": "https://api.github.com/users/leseb/following{/other_user}",
      "gists_url": "https://api.github.com/users/leseb/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/leseb",
      "id": 912735,
      "login": "leseb",
      "node_id": "MDQ6VXNlcjkxMjczNQ==",
      "organizations_url": "https://api.github.com/users/leseb/orgs",
      "received_events_url": "https://api.github.com/users/leseb/received_events",
      "repos_url": "https://api.github.com/users/leseb/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/leseb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/leseb/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/leseb"
    },
    "description": "",
    "due_on": null,
    "html_url": "https://github.com/rook/rook/milestone/13",
    "id": 4594913,
    "labels_url": "https://api.github.com/repos/rook/rook/milestones/13/labels",
    "node_id": "MDk6TWlsZXN0b25lNDU5NDkxMw==",
    "number": 13,
    "open_issues": 0,
    "state": "closed",
    "title": "1.2",
    "updated_at": "2020-09-18T21:21:55Z",
    "url": "https://api.github.com/repos/rook/rook/milestones/13"
  },
  "node_id": "MDU6SXNzdWU1ODA2Mjg4OTg=",
  "number": 5022,
  "performed_via_github_app": null,
  "repository_url": "https://api.github.com/repos/rook/rook",
  "state": "closed",
  "title": "After upgrade from 1.2.4 to 1.2.6 rook-ceph-osd-prepare fails at sda1 which contains root filesystem and should not be touched",
  "updated_at": "2020-03-26T12:15:41Z",
  "url": "https://api.github.com/repos/rook/rook/issues/5022",
  "user": {
    "avatar_url": "https://avatars2.githubusercontent.com/u/343754?v=4",
    "events_url": "https://api.github.com/users/amiga23/events{/privacy}",
    "followers_url": "https://api.github.com/users/amiga23/followers",
    "following_url": "https://api.github.com/users/amiga23/following{/other_user}",
    "gists_url": "https://api.github.com/users/amiga23/gists{/gist_id}",
    "gravatar_id": "",
    "html_url": "https://github.com/amiga23",
    "id": 343754,
    "login": "amiga23",
    "node_id": "MDQ6VXNlcjM0Mzc1NA==",
    "organizations_url": "https://api.github.com/users/amiga23/orgs",
    "received_events_url": "https://api.github.com/users/amiga23/received_events",
    "repos_url": "https://api.github.com/users/amiga23/repos",
    "site_admin": false,
    "starred_url": "https://api.github.com/users/amiga23/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/amiga23/subscriptions",
    "type": "User",
    "url": "https://api.github.com/users/amiga23"
  }
}